ignore:
- "Tests"
- "Sources/PrimitiveTypes/DivModUtils.swift"
coverage:
  status:
    patch:
      default:
        enabled: true
        target: 50%     
        threshold: 0  
    project:
      default:
        enabled: false
